---
# tasks file for install_nginx
---
# tasks file for httpd
- name: Nginxインストール
  yum:
    name: nginx
    state: latest

- name: サービス有効化
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: ファイアウォール穴あけ(http)
  firewalld:
    service: http
    permanent: yes
    state: enabled
  ignore_errors: true
  notify:
    - restart firewalld

- name: ファイアウォール穴あけ(https)
  firewalld:
    service: https
    permanent: yes
    state: enabled
  ignore_errors: true
  notify:
    - restart firewalld
