---
# tasks file for docker container run
- name: docker container run
  shell: docker run -d -it -p "{{ docker_host_port }}":"{{ docker_container_port }}" --name "{{ docker_container_name }}" "{{ docker_image }}"
  register: result

- name: debug
  debug: var=result
