on:
  push:
    branches:
      - 'dev'
    paths:
      - 'Docker/blog-a/**'
      - '.github/workflows/blog-a.yml'
jobs:
  DeployBlog:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      # Deploy
      - name: deploy artifacts
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -p 22 -H 116.80.61.252 >> ~/.ssh/known_hosts  # Blog
          cp -r Docker/blog-a/public/ Ansible/playbooks/files/
          ansible-playbook -i Ansible/inventory/hosts.yml Ansible/playbooks/blog-deploy.yml --private-key ~/.ssh/id_rsa
      #
